name: "Scrap jobs from hackernews"

description: "Scrap jobs from hackernews"

inputs:
  gh_token:
    description: 'GitHub access token with Repo scope'
    required: false
    default: ${{ github.token }}

runs:
  using: "docker"
  image: "Dockerfile"