name: "Search hackernews jobs"

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
    

jobs:
  action:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
     
      - name: "Searching for jobs"
        uses: "./.github/actions/go-scrap"