name: "Search ycombinator jobs"

on:
  push:
    branches:
      - main
      - dev

jobs:
  action:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
     
      - name: "Searching for jobs"
        uses: "./.github/actions/go-scrap"